name: CI/CD pipeline

on: 
  workflow_dispatch: # Only runs manually if you trigger it

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "This is an empty pipeline. Nothing runs on push or PR."

  deploy:
    runs-on: ubuntu-latest
    # Make sure this job depends on a job named "security" if needed
    # If you don't have a "security" job, remove the `needs` line
    # needs: security
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download coverage artifact (if present)
        uses: actions/download-artifact@v4
        with:
          name: coverage-html
          path: artifacts/coverage-html
        continue-on-error: true

      - name: Download lint report (if present)
        uses: actions/download-artifact@v4
        with:
          name: lint-report
          path: artifacts/lint
        continue-on-error: true

      - name: Download security report (if present)
        uses: actions/download-artifact@v4
        with:
          name: security-report
          path: artifacts/security
        continue-on-error: true

      - name: Create deployment package
        run: |
          echo "Creating simple deployment package..."
          rm -f deployment-package.zip || true
          # Compile python files (best-effort)
          python -m compileall -b -f src || true
          # Create zip containing source, compiled files, and any artifacts
          zip -r deployment-package.zip src artifacts README.md requirements.txt || true
          echo "Created deployment-package.zip"
          ls -lh deployment-package.zip || true
          unzip -l deployment-package.zip || true

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deployment-zip
          path: deployment-package.zip
